export PROJECT_NAME = roadhog
export FLASK_APP = $(PROJECT_NAME).py
export FLASK_TEST_CONFIG = $(PWD)/$(PROJECT_NAME)/tests/testing_settings.py

# Python env
VENV = $(PWD)/.env
PIP = $(VENV)/bin/pip
PYTHON = $(VENV)/bin/python
PYTEST = $(VENV)/bin/py.test
FLASK = $(VENV)/bin/flask

